{{/*
#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
*/}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ita-by-ansible-towermaster-sync.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ita-by-ansible-towermaster-sync.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ita-by-ansible-towermaster-sync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ita-by-ansible-towermaster-sync.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ita-by-ansible-towermaster-sync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ template "ita-by-ansible-towermaster-sync.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $define := .Values.global -}}
            {{-   range $config, $value := $define.config }}
            - name: {{ $config }}
              valueFrom:
                configMapKeyRef:
                  name: params-{{ $define.name }}
                  key: {{ $config }}
            {{-   end -}}
            {{-   range $secret, $value := $define.secret }}
            - name: {{ $secret }}
              valueFrom:
                secretKeyRef:
                  name: secret-{{ $define.name }}
                  key: {{ $secret }}
            {{-   end }}
            {{- end -}}
            {{ range $config, $value := .Values.extraEnv }}
            - name: {{ $config }}
              valueFrom:
                configMapKeyRef:
                  name: params-{{ template "ita-by-ansible-towermaster-sync.fullname" $ }}
                  key: {{ $config }}
            {{- end }}
          volumeMounts:
            - name: volume-{{ template "ita-by-ansible-towermaster-sync.fullname" . }}-storage
              mountPath: {{ .Values.persistence.mountPath.storage }}
            - name: volume-{{ template "ita-by-ansible-towermaster-sync.fullname" . }}-homedir
              mountPath: {{ .Values.persistence.mountPath.homeDir }}
            - name: volume-{{ template "ita-by-ansible-towermaster-sync.fullname" . }}-tmp
              mountPath: {{ .Values.persistence.mountPath.tmp }}
          # livenessProbe:
          #   tcpSocket:
          #     port: 8080
          #   # httpGet:
          #   #   path: /
          #   #   port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10            
          # readinessProbe:
          #   tcpSocket:
          #     port: 8080
          #   # httpGet:
          #   #   path: /
          #   #   port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10            
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: volume-{{ template "ita-by-ansible-towermaster-sync.fullname" . }}-storage
          {{- if and .Values.global.itaGlobalDefinition.persistence.enabled }}
          persistentVolumeClaim:
            claimName: pvc-{{ .Values.global.itaGlobalDefinition.name }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: volume-{{ template "ita-by-ansible-towermaster-sync.fullname" . }}-homedir
          emptyDir: {}
        - name: volume-{{ template "ita-by-ansible-towermaster-sync.fullname" . }}-pid
          emptyDir: {}
        - name: volume-{{ template "ita-by-ansible-towermaster-sync.fullname" . }}-socket
          emptyDir: {}
        - name: volume-{{ template "ita-by-ansible-towermaster-sync.fullname" . }}-tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
