# Default values for Exastro IT Automation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  itaGlobalDefinition:
    name: ita-global
    enabled: true
    image:
      registry: "docker.io"
      organization: exastro
      package: exastro-it-automation
    config:
      DEFAULT_LANGUAGE: "ja"
      LANGUAGE: "en"
      CONTAINER_BASE: "kubernetes"
      TZ: "Asia/Tokyo"
      STORAGEPATH: "/storage/"
    secret:
      ENCRYPT_KEY: ""
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      size: 10Gi
      volumeType: hostPath # e.g.) hostPath or AKS
      storageClass: "-" # e.g.) azurefile or - (None)
      # matchLabels:
      #   release: "stable"
      # matchExpressions:
      #   - {key: environment, operator: In, values: [dev]}
  gitlabDefinition:
    name: gitlab
    enabled: true
    config:
      GITLAB_PROTOCOL: "http"
      GITLAB_HOST: "gitlab.exastro-platform.svc"
      GITLAB_PORT: "80"
    secret:
      GITLAB_ROOT_TOKEN: ""
  itaDatabaseDefinition:
    name: ita-database
    enabled: true
    config:
      DB_VENDOR: "mariadb"
      DB_HOST: "mariadb.exastro-platform.svc"
      DB_PORT: "3306"
      DB_DATABASE: "ITA_DB"
    secret:
      DB_ADMIN_USER: ""
      DB_ADMIN_PASSWORD: ""
      DB_USER: ""
      DB_PASSWORD: ""

ita-api-admin:
  replicaCount: 1
  image:
    repository: "exastro/exastro-it-automation-api-admin"
    tag: "2.0.2"
    pullPolicy: IfNotPresent

ita-api-organization:
  replicaCount: 1
  image:
    repository: "exastro/exastro-it-automation-api-organization"
    tag: "2.0.2"
    pullPolicy: IfNotPresent

ita-by-ansible-execute:
  replicaCount: 1
  image:
    repository: "exastro/exastro-it-automation-by-ansible-execute"
    tag: "2.0.2"
    pullPolicy: IfNotPresent
  extraEnv:
    EXECUTE_INTERVAL: "10"
    ANSIBLE_AGENT_IMAGE: "exastro/exastro-it-automation-by-ansible-agent"
    ANSIBLE_AGENT_IMAGE_TAG: "2.0.2"
  serviceAccount:
    create: false
    name: "ita-by-ansible-execute-sa"

ita-by-ansible-legacy-role-vars-listup:
  replicaCount: 1
  extraEnv:
    EXECUTE_INTERVAL: "10"
  image:
    repository: "exastro/exastro-it-automation-by-ansible-legacy-role-vars-listup"
    tag: "2.0.2"
    pullPolicy: IfNotPresent

ita-by-ansible-towermaster-sync:
  replicaCount: 1
  extraEnv:
    EXECUTE_INTERVAL: "10"
  image:
    repository: "exastro/exastro-it-automation-by-ansible-towermaster-sync"
    tag: "2.0.2"
    pullPolicy: IfNotPresent

ita-by-conductor-synchronize:
  replicaCount: 1
  extraEnv:
    EXECUTE_INTERVAL: "10"
  image:
    repository: "exastro/exastro-it-automation-by-conductor-synchronize"
    tag: "2.0.2"
    pullPolicy: IfNotPresent

ita-by-menu-create:
  replicaCount: 1
  extraEnv:
    EXECUTE_INTERVAL: "10"
  image:
    repository: "exastro/exastro-it-automation-by-menu-create"
    tag: "2.0.2"
    pullPolicy: IfNotPresent

ita-database-setup-job:
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

ita-web-server:
  replicaCount: 1
  image:
    repository: "exastro/exastro-it-automation-web-server"
    tag: "2.0.2"
    pullPolicy: IfNotPresent
